//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("db_recomendeModel", "FK_tb_comentario_tb_usuario", "tb_usuario", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Projeto_Recomende.tb_usuario), "tb_comentario", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Projeto_Recomende.tb_comentario), true)]
[assembly: EdmRelationshipAttribute("db_recomendeModel", "FK_tb_filme_tb_comentario", "tb_comentario", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Projeto_Recomende.tb_comentario), "tb_filme", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Projeto_Recomende.tb_filme), true)]
[assembly: EdmRelationshipAttribute("db_recomendeModel", "FK_tb_filme_tb_genero", "tb_genero", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Projeto_Recomende.tb_genero), "tb_filme", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Projeto_Recomende.tb_filme), true)]
[assembly: EdmRelationshipAttribute("db_recomendeModel", "FK_tb_recomendacoes_tb_filme", "tb_filme", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Projeto_Recomende.tb_filme), "tb_recomendacoes", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Projeto_Recomende.tb_recomendacoes), true)]
[assembly: EdmRelationshipAttribute("db_recomendeModel", "FK_tb_usuario_tb_grupos", "tb_grupos", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Projeto_Recomende.tb_grupos), "tb_usuario", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Projeto_Recomende.tb_usuario), true)]
[assembly: EdmRelationshipAttribute("db_recomendeModel", "FK_tb_usuarioXrecomendacoes_tb_recomendacoes", "tb_recomendacoes", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Projeto_Recomende.tb_recomendacoes), "tb_usuarioXrecomendacoes", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Projeto_Recomende.tb_usuarioXrecomendacoes), true)]
[assembly: EdmRelationshipAttribute("db_recomendeModel", "FK_tb_usuarioXrecomendacoes_tb_usuario", "tb_usuario", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Projeto_Recomende.tb_usuario), "tb_usuarioXrecomendacoes", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Projeto_Recomende.tb_usuarioXrecomendacoes), true)]

#endregion

namespace Projeto_Recomende
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class recomendeEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new recomendeEntities object using the connection string found in the 'recomendeEntities' section of the application configuration file.
        /// </summary>
        public recomendeEntities() : base("name=recomendeEntities", "recomendeEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new recomendeEntities object.
        /// </summary>
        public recomendeEntities(string connectionString) : base(connectionString, "recomendeEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new recomendeEntities object.
        /// </summary>
        public recomendeEntities(EntityConnection connection) : base(connection, "recomendeEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sysdiagrams> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagrams>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagrams> _sysdiagrams;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tb_comentario> tb_comentario
        {
            get
            {
                if ((_tb_comentario == null))
                {
                    _tb_comentario = base.CreateObjectSet<tb_comentario>("tb_comentario");
                }
                return _tb_comentario;
            }
        }
        private ObjectSet<tb_comentario> _tb_comentario;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tb_filme> tb_filme
        {
            get
            {
                if ((_tb_filme == null))
                {
                    _tb_filme = base.CreateObjectSet<tb_filme>("tb_filme");
                }
                return _tb_filme;
            }
        }
        private ObjectSet<tb_filme> _tb_filme;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tb_genero> tb_genero
        {
            get
            {
                if ((_tb_genero == null))
                {
                    _tb_genero = base.CreateObjectSet<tb_genero>("tb_genero");
                }
                return _tb_genero;
            }
        }
        private ObjectSet<tb_genero> _tb_genero;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tb_grupos> tb_grupos
        {
            get
            {
                if ((_tb_grupos == null))
                {
                    _tb_grupos = base.CreateObjectSet<tb_grupos>("tb_grupos");
                }
                return _tb_grupos;
            }
        }
        private ObjectSet<tb_grupos> _tb_grupos;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tb_recomendacoes> tb_recomendacoes
        {
            get
            {
                if ((_tb_recomendacoes == null))
                {
                    _tb_recomendacoes = base.CreateObjectSet<tb_recomendacoes>("tb_recomendacoes");
                }
                return _tb_recomendacoes;
            }
        }
        private ObjectSet<tb_recomendacoes> _tb_recomendacoes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tb_usuario> tb_usuario
        {
            get
            {
                if ((_tb_usuario == null))
                {
                    _tb_usuario = base.CreateObjectSet<tb_usuario>("tb_usuario");
                }
                return _tb_usuario;
            }
        }
        private ObjectSet<tb_usuario> _tb_usuario;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tb_usuarioXrecomendacoes> tb_usuarioXrecomendacoes
        {
            get
            {
                if ((_tb_usuarioXrecomendacoes == null))
                {
                    _tb_usuarioXrecomendacoes = base.CreateObjectSet<tb_usuarioXrecomendacoes>("tb_usuarioXrecomendacoes");
                }
                return _tb_usuarioXrecomendacoes;
            }
        }
        private ObjectSet<tb_usuarioXrecomendacoes> _tb_usuarioXrecomendacoes;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sysdiagrams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosysdiagrams(sysdiagrams sysdiagrams)
        {
            base.AddObject("sysdiagrams", sysdiagrams);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tb_comentario EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotb_comentario(tb_comentario tb_comentario)
        {
            base.AddObject("tb_comentario", tb_comentario);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tb_filme EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotb_filme(tb_filme tb_filme)
        {
            base.AddObject("tb_filme", tb_filme);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tb_genero EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotb_genero(tb_genero tb_genero)
        {
            base.AddObject("tb_genero", tb_genero);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tb_grupos EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotb_grupos(tb_grupos tb_grupos)
        {
            base.AddObject("tb_grupos", tb_grupos);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tb_recomendacoes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotb_recomendacoes(tb_recomendacoes tb_recomendacoes)
        {
            base.AddObject("tb_recomendacoes", tb_recomendacoes);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tb_usuario EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotb_usuario(tb_usuario tb_usuario)
        {
            base.AddObject("tb_usuario", tb_usuario);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tb_usuarioXrecomendacoes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotb_usuarioXrecomendacoes(tb_usuarioXrecomendacoes tb_usuarioXrecomendacoes)
        {
            base.AddObject("tb_usuarioXrecomendacoes", tb_usuarioXrecomendacoes);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="db_recomendeModel", Name="sysdiagrams")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagrams : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sysdiagrams object.
        /// </summary>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="principal_id">Initial value of the principal_id property.</param>
        /// <param name="diagram_id">Initial value of the diagram_id property.</param>
        public static sysdiagrams Createsysdiagrams(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagrams sysdiagrams = new sysdiagrams();
            sysdiagrams.name = name;
            sysdiagrams.principal_id = principal_id;
            sysdiagrams.diagram_id = diagram_id;
            return sysdiagrams;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="db_recomendeModel", Name="tb_comentario")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tb_comentario : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tb_comentario object.
        /// </summary>
        /// <param name="id_comentario">Initial value of the id_comentario property.</param>
        /// <param name="desc_comentario">Initial value of the desc_comentario property.</param>
        /// <param name="dataComentario">Initial value of the dataComentario property.</param>
        /// <param name="id_usuario">Initial value of the id_usuario property.</param>
        public static tb_comentario Createtb_comentario(global::System.Int32 id_comentario, global::System.String desc_comentario, global::System.DateTime dataComentario, global::System.Int32 id_usuario)
        {
            tb_comentario tb_comentario = new tb_comentario();
            tb_comentario.id_comentario = id_comentario;
            tb_comentario.desc_comentario = desc_comentario;
            tb_comentario.dataComentario = dataComentario;
            tb_comentario.id_usuario = id_usuario;
            return tb_comentario;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_comentario
        {
            get
            {
                return _id_comentario;
            }
            set
            {
                if (_id_comentario != value)
                {
                    Onid_comentarioChanging(value);
                    ReportPropertyChanging("id_comentario");
                    _id_comentario = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_comentario");
                    Onid_comentarioChanged();
                }
            }
        }
        private global::System.Int32 _id_comentario;
        partial void Onid_comentarioChanging(global::System.Int32 value);
        partial void Onid_comentarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String desc_comentario
        {
            get
            {
                return _desc_comentario;
            }
            set
            {
                Ondesc_comentarioChanging(value);
                ReportPropertyChanging("desc_comentario");
                _desc_comentario = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("desc_comentario");
                Ondesc_comentarioChanged();
            }
        }
        private global::System.String _desc_comentario;
        partial void Ondesc_comentarioChanging(global::System.String value);
        partial void Ondesc_comentarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime dataComentario
        {
            get
            {
                return _dataComentario;
            }
            set
            {
                OndataComentarioChanging(value);
                ReportPropertyChanging("dataComentario");
                _dataComentario = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dataComentario");
                OndataComentarioChanged();
            }
        }
        private global::System.DateTime _dataComentario;
        partial void OndataComentarioChanging(global::System.DateTime value);
        partial void OndataComentarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_usuario
        {
            get
            {
                return _id_usuario;
            }
            set
            {
                Onid_usuarioChanging(value);
                ReportPropertyChanging("id_usuario");
                _id_usuario = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_usuario");
                Onid_usuarioChanged();
            }
        }
        private global::System.Int32 _id_usuario;
        partial void Onid_usuarioChanging(global::System.Int32 value);
        partial void Onid_usuarioChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("db_recomendeModel", "FK_tb_comentario_tb_usuario", "tb_usuario")]
        public tb_usuario tb_usuario
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_usuario>("db_recomendeModel.FK_tb_comentario_tb_usuario", "tb_usuario").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_usuario>("db_recomendeModel.FK_tb_comentario_tb_usuario", "tb_usuario").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tb_usuario> tb_usuarioReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_usuario>("db_recomendeModel.FK_tb_comentario_tb_usuario", "tb_usuario");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tb_usuario>("db_recomendeModel.FK_tb_comentario_tb_usuario", "tb_usuario", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("db_recomendeModel", "FK_tb_filme_tb_comentario", "tb_filme")]
        public EntityCollection<tb_filme> tb_filme
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tb_filme>("db_recomendeModel.FK_tb_filme_tb_comentario", "tb_filme");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tb_filme>("db_recomendeModel.FK_tb_filme_tb_comentario", "tb_filme", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="db_recomendeModel", Name="tb_filme")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tb_filme : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tb_filme object.
        /// </summary>
        /// <param name="cod_filme">Initial value of the cod_filme property.</param>
        /// <param name="nm_titulo">Initial value of the nm_titulo property.</param>
        /// <param name="id_genero">Initial value of the id_genero property.</param>
        /// <param name="id_comentario">Initial value of the id_comentario property.</param>
        public static tb_filme Createtb_filme(global::System.Int32 cod_filme, global::System.String nm_titulo, global::System.Int32 id_genero, global::System.Int32 id_comentario)
        {
            tb_filme tb_filme = new tb_filme();
            tb_filme.cod_filme = cod_filme;
            tb_filme.nm_titulo = nm_titulo;
            tb_filme.id_genero = id_genero;
            tb_filme.id_comentario = id_comentario;
            return tb_filme;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 cod_filme
        {
            get
            {
                return _cod_filme;
            }
            set
            {
                if (_cod_filme != value)
                {
                    Oncod_filmeChanging(value);
                    ReportPropertyChanging("cod_filme");
                    _cod_filme = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("cod_filme");
                    Oncod_filmeChanged();
                }
            }
        }
        private global::System.Int32 _cod_filme;
        partial void Oncod_filmeChanging(global::System.Int32 value);
        partial void Oncod_filmeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nm_titulo
        {
            get
            {
                return _nm_titulo;
            }
            set
            {
                Onnm_tituloChanging(value);
                ReportPropertyChanging("nm_titulo");
                _nm_titulo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nm_titulo");
                Onnm_tituloChanged();
            }
        }
        private global::System.String _nm_titulo;
        partial void Onnm_tituloChanging(global::System.String value);
        partial void Onnm_tituloChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String nm_tituloOriginal
        {
            get
            {
                return _nm_tituloOriginal;
            }
            set
            {
                Onnm_tituloOriginalChanging(value);
                ReportPropertyChanging("nm_tituloOriginal");
                _nm_tituloOriginal = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("nm_tituloOriginal");
                Onnm_tituloOriginalChanged();
            }
        }
        private global::System.String _nm_tituloOriginal;
        partial void Onnm_tituloOriginalChanging(global::System.String value);
        partial void Onnm_tituloOriginalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> dt_anoProducao
        {
            get
            {
                return _dt_anoProducao;
            }
            set
            {
                Ondt_anoProducaoChanging(value);
                ReportPropertyChanging("dt_anoProducao");
                _dt_anoProducao = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dt_anoProducao");
                Ondt_anoProducaoChanged();
            }
        }
        private Nullable<global::System.DateTime> _dt_anoProducao;
        partial void Ondt_anoProducaoChanging(Nullable<global::System.DateTime> value);
        partial void Ondt_anoProducaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String txt_sinopse
        {
            get
            {
                return _txt_sinopse;
            }
            set
            {
                Ontxt_sinopseChanging(value);
                ReportPropertyChanging("txt_sinopse");
                _txt_sinopse = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("txt_sinopse");
                Ontxt_sinopseChanged();
            }
        }
        private global::System.String _txt_sinopse;
        partial void Ontxt_sinopseChanging(global::System.String value);
        partial void Ontxt_sinopseChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String duracao
        {
            get
            {
                return _duracao;
            }
            set
            {
                OnduracaoChanging(value);
                ReportPropertyChanging("duracao");
                _duracao = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("duracao");
                OnduracaoChanged();
            }
        }
        private global::System.String _duracao;
        partial void OnduracaoChanging(global::System.String value);
        partial void OnduracaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String elenco
        {
            get
            {
                return _elenco;
            }
            set
            {
                OnelencoChanging(value);
                ReportPropertyChanging("elenco");
                _elenco = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("elenco");
                OnelencoChanged();
            }
        }
        private global::System.String _elenco;
        partial void OnelencoChanging(global::System.String value);
        partial void OnelencoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String genero
        {
            get
            {
                return _genero;
            }
            set
            {
                OngeneroChanging(value);
                ReportPropertyChanging("genero");
                _genero = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("genero");
                OngeneroChanged();
            }
        }
        private global::System.String _genero;
        partial void OngeneroChanging(global::System.String value);
        partial void OngeneroChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_genero
        {
            get
            {
                return _id_genero;
            }
            set
            {
                Onid_generoChanging(value);
                ReportPropertyChanging("id_genero");
                _id_genero = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_genero");
                Onid_generoChanged();
            }
        }
        private global::System.Int32 _id_genero;
        partial void Onid_generoChanging(global::System.Int32 value);
        partial void Onid_generoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String foto
        {
            get
            {
                return _foto;
            }
            set
            {
                OnfotoChanging(value);
                ReportPropertyChanging("foto");
                _foto = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("foto");
                OnfotoChanged();
            }
        }
        private global::System.String _foto;
        partial void OnfotoChanging(global::System.String value);
        partial void OnfotoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_comentario
        {
            get
            {
                return _id_comentario;
            }
            set
            {
                Onid_comentarioChanging(value);
                ReportPropertyChanging("id_comentario");
                _id_comentario = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_comentario");
                Onid_comentarioChanged();
            }
        }
        private global::System.Int32 _id_comentario;
        partial void Onid_comentarioChanging(global::System.Int32 value);
        partial void Onid_comentarioChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("db_recomendeModel", "FK_tb_filme_tb_comentario", "tb_comentario")]
        public tb_comentario tb_comentario
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_comentario>("db_recomendeModel.FK_tb_filme_tb_comentario", "tb_comentario").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_comentario>("db_recomendeModel.FK_tb_filme_tb_comentario", "tb_comentario").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tb_comentario> tb_comentarioReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_comentario>("db_recomendeModel.FK_tb_filme_tb_comentario", "tb_comentario");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tb_comentario>("db_recomendeModel.FK_tb_filme_tb_comentario", "tb_comentario", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("db_recomendeModel", "FK_tb_filme_tb_genero", "tb_genero")]
        public tb_genero tb_genero
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_genero>("db_recomendeModel.FK_tb_filme_tb_genero", "tb_genero").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_genero>("db_recomendeModel.FK_tb_filme_tb_genero", "tb_genero").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tb_genero> tb_generoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_genero>("db_recomendeModel.FK_tb_filme_tb_genero", "tb_genero");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tb_genero>("db_recomendeModel.FK_tb_filme_tb_genero", "tb_genero", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("db_recomendeModel", "FK_tb_recomendacoes_tb_filme", "tb_recomendacoes")]
        public EntityCollection<tb_recomendacoes> tb_recomendacoes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tb_recomendacoes>("db_recomendeModel.FK_tb_recomendacoes_tb_filme", "tb_recomendacoes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tb_recomendacoes>("db_recomendeModel.FK_tb_recomendacoes_tb_filme", "tb_recomendacoes", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="db_recomendeModel", Name="tb_genero")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tb_genero : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tb_genero object.
        /// </summary>
        /// <param name="id_genero">Initial value of the id_genero property.</param>
        /// <param name="tp_genero">Initial value of the tp_genero property.</param>
        public static tb_genero Createtb_genero(global::System.Int32 id_genero, global::System.String tp_genero)
        {
            tb_genero tb_genero = new tb_genero();
            tb_genero.id_genero = id_genero;
            tb_genero.tp_genero = tp_genero;
            return tb_genero;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_genero
        {
            get
            {
                return _id_genero;
            }
            set
            {
                if (_id_genero != value)
                {
                    Onid_generoChanging(value);
                    ReportPropertyChanging("id_genero");
                    _id_genero = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_genero");
                    Onid_generoChanged();
                }
            }
        }
        private global::System.Int32 _id_genero;
        partial void Onid_generoChanging(global::System.Int32 value);
        partial void Onid_generoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String tp_genero
        {
            get
            {
                return _tp_genero;
            }
            set
            {
                Ontp_generoChanging(value);
                ReportPropertyChanging("tp_genero");
                _tp_genero = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("tp_genero");
                Ontp_generoChanged();
            }
        }
        private global::System.String _tp_genero;
        partial void Ontp_generoChanging(global::System.String value);
        partial void Ontp_generoChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("db_recomendeModel", "FK_tb_filme_tb_genero", "tb_filme")]
        public EntityCollection<tb_filme> tb_filme
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tb_filme>("db_recomendeModel.FK_tb_filme_tb_genero", "tb_filme");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tb_filme>("db_recomendeModel.FK_tb_filme_tb_genero", "tb_filme", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="db_recomendeModel", Name="tb_grupos")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tb_grupos : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tb_grupos object.
        /// </summary>
        /// <param name="id_grupo">Initial value of the id_grupo property.</param>
        /// <param name="pontuacaoUsuario">Initial value of the pontuacaoUsuario property.</param>
        public static tb_grupos Createtb_grupos(global::System.Int32 id_grupo, global::System.Int32 pontuacaoUsuario)
        {
            tb_grupos tb_grupos = new tb_grupos();
            tb_grupos.id_grupo = id_grupo;
            tb_grupos.pontuacaoUsuario = pontuacaoUsuario;
            return tb_grupos;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_grupo
        {
            get
            {
                return _id_grupo;
            }
            set
            {
                if (_id_grupo != value)
                {
                    Onid_grupoChanging(value);
                    ReportPropertyChanging("id_grupo");
                    _id_grupo = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_grupo");
                    Onid_grupoChanged();
                }
            }
        }
        private global::System.Int32 _id_grupo;
        partial void Onid_grupoChanging(global::System.Int32 value);
        partial void Onid_grupoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 pontuacaoUsuario
        {
            get
            {
                return _pontuacaoUsuario;
            }
            set
            {
                OnpontuacaoUsuarioChanging(value);
                ReportPropertyChanging("pontuacaoUsuario");
                _pontuacaoUsuario = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("pontuacaoUsuario");
                OnpontuacaoUsuarioChanged();
            }
        }
        private global::System.Int32 _pontuacaoUsuario;
        partial void OnpontuacaoUsuarioChanging(global::System.Int32 value);
        partial void OnpontuacaoUsuarioChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("db_recomendeModel", "FK_tb_usuario_tb_grupos", "tb_usuario")]
        public EntityCollection<tb_usuario> tb_usuario
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tb_usuario>("db_recomendeModel.FK_tb_usuario_tb_grupos", "tb_usuario");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tb_usuario>("db_recomendeModel.FK_tb_usuario_tb_grupos", "tb_usuario", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="db_recomendeModel", Name="tb_recomendacoes")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tb_recomendacoes : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tb_recomendacoes object.
        /// </summary>
        /// <param name="cod_filme">Initial value of the cod_filme property.</param>
        /// <param name="id_recomendacao">Initial value of the id_recomendacao property.</param>
        public static tb_recomendacoes Createtb_recomendacoes(global::System.Int32 cod_filme, global::System.Int32 id_recomendacao)
        {
            tb_recomendacoes tb_recomendacoes = new tb_recomendacoes();
            tb_recomendacoes.cod_filme = cod_filme;
            tb_recomendacoes.id_recomendacao = id_recomendacao;
            return tb_recomendacoes;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 cod_filme
        {
            get
            {
                return _cod_filme;
            }
            set
            {
                Oncod_filmeChanging(value);
                ReportPropertyChanging("cod_filme");
                _cod_filme = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("cod_filme");
                Oncod_filmeChanged();
            }
        }
        private global::System.Int32 _cod_filme;
        partial void Oncod_filmeChanging(global::System.Int32 value);
        partial void Oncod_filmeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_recomendacao
        {
            get
            {
                return _id_recomendacao;
            }
            set
            {
                if (_id_recomendacao != value)
                {
                    Onid_recomendacaoChanging(value);
                    ReportPropertyChanging("id_recomendacao");
                    _id_recomendacao = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_recomendacao");
                    Onid_recomendacaoChanged();
                }
            }
        }
        private global::System.Int32 _id_recomendacao;
        partial void Onid_recomendacaoChanging(global::System.Int32 value);
        partial void Onid_recomendacaoChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("db_recomendeModel", "FK_tb_recomendacoes_tb_filme", "tb_filme")]
        public tb_filme tb_filme
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_filme>("db_recomendeModel.FK_tb_recomendacoes_tb_filme", "tb_filme").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_filme>("db_recomendeModel.FK_tb_recomendacoes_tb_filme", "tb_filme").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tb_filme> tb_filmeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_filme>("db_recomendeModel.FK_tb_recomendacoes_tb_filme", "tb_filme");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tb_filme>("db_recomendeModel.FK_tb_recomendacoes_tb_filme", "tb_filme", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("db_recomendeModel", "FK_tb_usuarioXrecomendacoes_tb_recomendacoes", "tb_usuarioXrecomendacoes")]
        public EntityCollection<tb_usuarioXrecomendacoes> tb_usuarioXrecomendacoes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tb_usuarioXrecomendacoes>("db_recomendeModel.FK_tb_usuarioXrecomendacoes_tb_recomendacoes", "tb_usuarioXrecomendacoes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tb_usuarioXrecomendacoes>("db_recomendeModel.FK_tb_usuarioXrecomendacoes_tb_recomendacoes", "tb_usuarioXrecomendacoes", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="db_recomendeModel", Name="tb_usuario")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tb_usuario : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tb_usuario object.
        /// </summary>
        /// <param name="id_usuario">Initial value of the id_usuario property.</param>
        /// <param name="nm_usuario">Initial value of the nm_usuario property.</param>
        /// <param name="email">Initial value of the email property.</param>
        /// <param name="senha">Initial value of the senha property.</param>
        /// <param name="id_grupo">Initial value of the id_grupo property.</param>
        public static tb_usuario Createtb_usuario(global::System.Int32 id_usuario, global::System.String nm_usuario, global::System.String email, global::System.String senha, global::System.Int32 id_grupo)
        {
            tb_usuario tb_usuario = new tb_usuario();
            tb_usuario.id_usuario = id_usuario;
            tb_usuario.nm_usuario = nm_usuario;
            tb_usuario.email = email;
            tb_usuario.senha = senha;
            tb_usuario.id_grupo = id_grupo;
            return tb_usuario;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_usuario
        {
            get
            {
                return _id_usuario;
            }
            set
            {
                if (_id_usuario != value)
                {
                    Onid_usuarioChanging(value);
                    ReportPropertyChanging("id_usuario");
                    _id_usuario = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_usuario");
                    Onid_usuarioChanged();
                }
            }
        }
        private global::System.Int32 _id_usuario;
        partial void Onid_usuarioChanging(global::System.Int32 value);
        partial void Onid_usuarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nm_usuario
        {
            get
            {
                return _nm_usuario;
            }
            set
            {
                Onnm_usuarioChanging(value);
                ReportPropertyChanging("nm_usuario");
                _nm_usuario = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nm_usuario");
                Onnm_usuarioChanged();
            }
        }
        private global::System.String _nm_usuario;
        partial void Onnm_usuarioChanging(global::System.String value);
        partial void Onnm_usuarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String senha
        {
            get
            {
                return _senha;
            }
            set
            {
                OnsenhaChanging(value);
                ReportPropertyChanging("senha");
                _senha = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("senha");
                OnsenhaChanged();
            }
        }
        private global::System.String _senha;
        partial void OnsenhaChanging(global::System.String value);
        partial void OnsenhaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_grupo
        {
            get
            {
                return _id_grupo;
            }
            set
            {
                Onid_grupoChanging(value);
                ReportPropertyChanging("id_grupo");
                _id_grupo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_grupo");
                Onid_grupoChanged();
            }
        }
        private global::System.Int32 _id_grupo;
        partial void Onid_grupoChanging(global::System.Int32 value);
        partial void Onid_grupoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String end_foto
        {
            get
            {
                return _end_foto;
            }
            set
            {
                Onend_fotoChanging(value);
                ReportPropertyChanging("end_foto");
                _end_foto = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("end_foto");
                Onend_fotoChanged();
            }
        }
        private global::System.String _end_foto;
        partial void Onend_fotoChanging(global::System.String value);
        partial void Onend_fotoChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("db_recomendeModel", "FK_tb_comentario_tb_usuario", "tb_comentario")]
        public EntityCollection<tb_comentario> tb_comentario
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tb_comentario>("db_recomendeModel.FK_tb_comentario_tb_usuario", "tb_comentario");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tb_comentario>("db_recomendeModel.FK_tb_comentario_tb_usuario", "tb_comentario", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("db_recomendeModel", "FK_tb_usuario_tb_grupos", "tb_grupos")]
        public tb_grupos tb_grupos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_grupos>("db_recomendeModel.FK_tb_usuario_tb_grupos", "tb_grupos").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_grupos>("db_recomendeModel.FK_tb_usuario_tb_grupos", "tb_grupos").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tb_grupos> tb_gruposReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_grupos>("db_recomendeModel.FK_tb_usuario_tb_grupos", "tb_grupos");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tb_grupos>("db_recomendeModel.FK_tb_usuario_tb_grupos", "tb_grupos", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("db_recomendeModel", "FK_tb_usuarioXrecomendacoes_tb_usuario", "tb_usuarioXrecomendacoes")]
        public EntityCollection<tb_usuarioXrecomendacoes> tb_usuarioXrecomendacoes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tb_usuarioXrecomendacoes>("db_recomendeModel.FK_tb_usuarioXrecomendacoes_tb_usuario", "tb_usuarioXrecomendacoes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tb_usuarioXrecomendacoes>("db_recomendeModel.FK_tb_usuarioXrecomendacoes_tb_usuario", "tb_usuarioXrecomendacoes", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="db_recomendeModel", Name="tb_usuarioXrecomendacoes")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tb_usuarioXrecomendacoes : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tb_usuarioXrecomendacoes object.
        /// </summary>
        /// <param name="id_usuario_recom">Initial value of the id_usuario_recom property.</param>
        /// <param name="id_usuario">Initial value of the id_usuario property.</param>
        /// <param name="id_recomende">Initial value of the id_recomende property.</param>
        public static tb_usuarioXrecomendacoes Createtb_usuarioXrecomendacoes(global::System.Int32 id_usuario_recom, global::System.Int32 id_usuario, global::System.Int32 id_recomende)
        {
            tb_usuarioXrecomendacoes tb_usuarioXrecomendacoes = new tb_usuarioXrecomendacoes();
            tb_usuarioXrecomendacoes.id_usuario_recom = id_usuario_recom;
            tb_usuarioXrecomendacoes.id_usuario = id_usuario;
            tb_usuarioXrecomendacoes.id_recomende = id_recomende;
            return tb_usuarioXrecomendacoes;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_usuario_recom
        {
            get
            {
                return _id_usuario_recom;
            }
            set
            {
                if (_id_usuario_recom != value)
                {
                    Onid_usuario_recomChanging(value);
                    ReportPropertyChanging("id_usuario_recom");
                    _id_usuario_recom = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_usuario_recom");
                    Onid_usuario_recomChanged();
                }
            }
        }
        private global::System.Int32 _id_usuario_recom;
        partial void Onid_usuario_recomChanging(global::System.Int32 value);
        partial void Onid_usuario_recomChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_usuario
        {
            get
            {
                return _id_usuario;
            }
            set
            {
                Onid_usuarioChanging(value);
                ReportPropertyChanging("id_usuario");
                _id_usuario = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_usuario");
                Onid_usuarioChanged();
            }
        }
        private global::System.Int32 _id_usuario;
        partial void Onid_usuarioChanging(global::System.Int32 value);
        partial void Onid_usuarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_recomende
        {
            get
            {
                return _id_recomende;
            }
            set
            {
                Onid_recomendeChanging(value);
                ReportPropertyChanging("id_recomende");
                _id_recomende = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_recomende");
                Onid_recomendeChanged();
            }
        }
        private global::System.Int32 _id_recomende;
        partial void Onid_recomendeChanging(global::System.Int32 value);
        partial void Onid_recomendeChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("db_recomendeModel", "FK_tb_usuarioXrecomendacoes_tb_recomendacoes", "tb_recomendacoes")]
        public tb_recomendacoes tb_recomendacoes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_recomendacoes>("db_recomendeModel.FK_tb_usuarioXrecomendacoes_tb_recomendacoes", "tb_recomendacoes").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_recomendacoes>("db_recomendeModel.FK_tb_usuarioXrecomendacoes_tb_recomendacoes", "tb_recomendacoes").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tb_recomendacoes> tb_recomendacoesReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_recomendacoes>("db_recomendeModel.FK_tb_usuarioXrecomendacoes_tb_recomendacoes", "tb_recomendacoes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tb_recomendacoes>("db_recomendeModel.FK_tb_usuarioXrecomendacoes_tb_recomendacoes", "tb_recomendacoes", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("db_recomendeModel", "FK_tb_usuarioXrecomendacoes_tb_usuario", "tb_usuario")]
        public tb_usuario tb_usuario
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_usuario>("db_recomendeModel.FK_tb_usuarioXrecomendacoes_tb_usuario", "tb_usuario").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_usuario>("db_recomendeModel.FK_tb_usuarioXrecomendacoes_tb_usuario", "tb_usuario").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tb_usuario> tb_usuarioReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_usuario>("db_recomendeModel.FK_tb_usuarioXrecomendacoes_tb_usuario", "tb_usuario");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tb_usuario>("db_recomendeModel.FK_tb_usuarioXrecomendacoes_tb_usuario", "tb_usuario", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
